name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: ${{ matrix.ros_distro }}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
          ros_distro: [rolling]
    steps:
    - uses: actions/checkout@v2
    - name: Install Cyclone DDS
      run: sudo apt install ros-${{ matrix.ros_distro }}-rmw-cyclonedds-cpp -y
    - name: Install geometry_msgs
      run: sudo apt install ros-${{ matrix.ros_distro }}-geometry-msgs -y
    - name: Install nav_msgs
      run: sudo apt install ros-${{ matrix.ros_distro }}-nav-msgs -y
    - name: Install rosidl-default-generators
      run: sudo apt install ros-${{ matrix.ros_distro }}-rosidl-default-generators -y
    - name: Install geographic_msgs
      run: sudo apt install ros-${{ matrix.ros_distro }}-geographic-msgs -y
    - name: Install bondcpp
      run: sudo apt install ros-${{ matrix.ros_distro }}-bondcpp -y
    - name: Install angles
      run: sudo apt install ros-${{ matrix.ros_distro }}-angles -y
    - name: Install test_msgs
      run: sudo apt install ros-${{ matrix.ros_distro }}-test-msgs -y
    - name: Build and run tests
      id: action-ros-ci
      uses: ros-tooling/action-ros-ci@v0.3.11
      with:
        import-token: ${{ secrets.GITHUB_TOKEN }}
        target-ros2-distro: ${{ matrix.ros_distro }}
        vcs-repo-file-url: "${{ github.workspace }}/.github/deps.repos"
        rosdep-check: true
    - uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
